### ISSUE TITLE
А можно уточнить, что это такое за конструкция?

### ISSUE THREAD

**Issue by aar87** [Avganets228/Practice#1]
https://github.com/Avganets228/Practice/blob/99d2f29f577619033c86d97375e9668c7d71e8aa/SMTP_Mail.py#L38

**Comment by Avganets228** [comment]
С данным скриптом не разобрался. Данная конструкция была в изначальном скрипте, я так понял это js, не понял назначение этой строки

**Comment by aar87** [comment]
Судя по синтаксису это не js, а на php больше похоже. Лучше не использовать то, что не понимаешь
