### ISSUE TITLE
Точка с запятой? Это точно python?

### ISSUE THREAD

**Issue by aar87** [Avganets228/Practice#2]
https://github.com/Avganets228/Practice/blob/99d2f29f577619033c86d97375e9668c7d71e8aa/SMTP_Mail.py#L10

**Comment by Avganets228** [comment]
Аналогично не понял, назначение данной строки

**Comment by aar87** [comment]
Я думал это ты пишешь код, или у кого тогда спросить? ) Кстати filet переводится как филе, странное решение

**Comment by Avganets228** [comment]
#!/usr/bin/perl

use Mail::Internet;

my $message = Mail::Internet -> new([ <> ]);                    # Получение письма

exit 69 if ($message->get(From) !~ /\@tayle\.com|\@tayle\.ru/);             # service unavailable if sent not from [test.net](http://test.net/) domain

my $filet = '/home/priceman/priceDil.txt';   # файл со списком адресов

open(RCPT,, $filet)

        or die "File not '$filet' found $!";                             # get recipients from file which name based on Subject string

 

# дальше идет формирование рассылочного письма, отправка идет с таймаутом в 5 секунд.

while ( my $bcc = <RCPT> ) {

$message->replace('To', "$bcc");                                    # empty To field

$message->replace('Cc', "");                                    # empty Cc field

$message->replace('From', "Tayle <priceman\@[tayle.ru](http://tayle.ru/)>");

$message->replace('Sender', "Tayle <priceman\@[tayle.ru](http://tayle.ru/)>");

$message->replace('Bcc', "");                                 # put all recipients to Bcc field

$message->replace('Subject', $message->get(Subject));           # replace Subject field

$message->replace('X-Original-To', "priceman\@[tayle.ru](http://tayle.ru/)");

$message->replace('Delivered-To', "priceman\@[tayle.ru](http://tayle.ru/)");

$message->smtpsend();                                           # send this shit

sleep(5);

}

close (RCPT);

exit 0;

**Comment by Avganets228** [comment]
вот этот кусок мне скинули

**Comment by aar87** [comment]
Значит это perl

#!/usr/bin/perl
