### ISSUE TITLE
Telebot это стандартная библиотека python? Какой версией python вы пользуетесь?

### ISSUE THREAD

**Issue by aar87** [Avganets228/Practice#3]
https://github.com/Avganets228/Practice/blob/99d2f29f577619033c86d97375e9668c7d71e8aa/IP_Checkout.py#L2

**Comment by Avganets228** [comment]
Telebot устанавливается через pip instal, Python 3.10

**Comment by aar87** [comment]
Тогда это должно быть указано в зависимостях, ну или на крайний случай в описании.

**Comment by Avganets228** [comment]
Добавил описание
