### ISSUE TITLE
А почему тут именно через пробел нужно путь указывать?

### ISSUE THREAD

**Issue by aar87** [Avganets228/Practice#4]
https://github.com/Avganets228/Practice/blob/99d2f29f577619033c86d97375e9668c7d71e8aa/Archive_Save.py#L15

**Comment by Avganets228** [comment]
Мне показалось что это удобнее для вводящего путь

**Comment by aar87** [comment]
А почему тогда archiver не парсит пробелы? Это не рабочий код: archived_file = string + '/' + filename

**Comment by Avganets228** [comment]
Исправил
